version: '3.8'

services:
  option-api:
    image: python:3.12-slim
    container_name: option-api
    network_mode: host
    working_dir: /app
    volumes:
      - /volume1/docker/option-api:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             python app.py"
    environment:
      - TZ=Europe/Amsterdam
      - DB_HOST=192.168.1.200
      - DB_USER=remoteuser
      - DB_PASS=T3l3foon32#123
      - DB_NAME=optionsdb
      - DB_PORT=3306
    restart: unless-stopped

  option-scraper:
    image: python:3.12-slim
    container_name: option-scraper
    network_mode: host
    working_dir: /app
    volumes:
      - /volume1/docker/option-api:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             while true; do python beursduivel.py; sleep 3600; done"
    environment:
      - TZ=Europe/Amsterdam
      - DB_HOST=192.168.1.200
      - DB_USER=remoteuser
      - DB_PASS=T3l3foon32#123
      - DB_NAME=optionsdb
      - DB_PORT=3306
    restart: unless-stopped

  sentiment-tracker:
    image: python:3.12-slim
    container_name: sentiment-tracker
    network_mode: host
    working_dir: /app
    volumes:
      - /volume1/docker/option-api:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             while true; do python sentiment_tracker.py; sleep 86400; done"
      # 86400 = 24 uur in seconden
    environment:
      - TZ=Europe/Amsterdam
      - DB_HOST=192.168.1.200
      - DB_USER=remoteuser
      - DB_PASS=T3l3foon32#123
      - DB_NAME=optionsdb
      - DB_PORT=3306
    restart: unless-stopped