[tool.black]
line-length = 100
target-version = ['py311']
extend-exclude = '''
(
  archive/
  | venv/
  | \.venv/
)
'''

[tool.ruff]
line-length = 100
exclude = [
  ".venv",
  "venv",
  "archive",
  "__pycache__",
]

[tool.ruff.lint]
# Keep ruff minimal and non-intrusive: only Pyflakes (F) for real errors
select = ["F"]
ignore = []
