# Portainer stack: ETL-only (run once and exit)
# Paste into Portainer > Stacks > Add stack, or upload this file.

services:
  daily-etl-once:
    image: ghcr.io/koenm-bit/option-data-collector:latest
    container_name: daily-etl-once
    environment:
      - TZ=Europe/Amsterdam
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT-3306}
    # Override entrypoint mode to run the ETL once (no 24h loop)
    command: ["python", "-m", "app.etl.daily_etl"]
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
